const CARDS = {
	"hero_soldier" : [2, 4, "unit", "Um resistente soldado", "", 1],
	"hero_archer" : [4, 1, "unit", "Um arqueiro habilidoso", "", 2],
	"hero_mage" : [5, 2, "unit", "Um elfo mago poderoso", "", 3],
	"hero_knight" : [4, 7, "unit", "*Pode atacar duas vezes", "res://scripts/abilities/attack_twice.gd", 4],
	"hero_duelist" : [5, 2, "unit", "Um elfo mestre com a espada", "", 3],
	"hero_spear" : [5, 2, "unit", "Um elfo mestre com a lança", "", 2],
	"hero_arrows": [null, null, "magic", "*Causa 1 de dano a todas as cartas do oponente", "res://scripts/abilities/arrows.gd", 2],
	"hero_balista": [null, null, "magic", "*Causa 2 de dano diretamente ao oponente", "res://scripts/abilities/balista.gd", 3],
	"villain_demon" : [2, 4, "unit", "Um demonio comum", "", 1],
	"villain_soldier" : [4, 1, "unit", "Um esqueleto soldado", "", 2],
	"villain_pyro" : [5, 2, "unit", "Um demonio piromante", "", 3],
	"villain_death" : [4, 7, "unit", "*Pode atacar duas vezes", "res://scripts/abilities/attack_twice.gd", 4],
	"villain_trident" : [5, 2, "unit", "Um demonio voador", "", 3],
	"villain_archer" : [5, 2, "unit", "Um esqueleto arqueiro", "", 2],
	"villain_decay": [null, null, "magic", "*Reduz 1 de ataque de todas as cartas do oponente", "res://scripts/abilities/decay.gd", 2],
	"villain_hellfire": [null, null, "magic", "*Causa 2 de dano a uma unit do oponente e causa 1 as adjacentes", "res://scripts/abilities/hellfire.gd", 3],
	"pirate_soldier" : [2, 4, "unit", "Um pirata comum", "", 1],
	"pirate_pistol" : [4, 1, "unit", "Um pirata com pistolas", "", 2],
	"pirate_spear" : [5, 2, "unit", "Um anão pirata arpoeiro", "", 2],
	"pirate_cannon" : [4, 7, "unit", "*Pode atacar duas vezes", "res://scripts/abilities/attack_twice.gd", 4],
	"pirate_dual" : [5, 2, "unit", "Um pirata mestre dos sabres", "", 3],
	"pirate_bomb" : [5, 2, "unit", "Um pirata mestre dos explosivos", "", 3],
	"pirate_spell1": [null, null, "magic", "", "", 2],
	"pirate_spell2": [null, null, "magic", "", "", 3],
	"green_warrior" : [2, 4, "unit", "Um orc burro", "", 1],
	"green_sword" : [4, 1, "unit", "Um goblin com espadão", "", 2],
	"green_mace" : [5, 2, "unit", "Um orc com maça de ferro", "", 2],
	"green_axe" : [4, 7, "unit", "*Pode atacar duas vezes", "res://scripts/abilities/attack_twice.gd", 4],
	"green_dual" : [5, 2, "unit", "Um orc com dois espadões", "", 3],
	"green_mage" : [5, 2, "unit", "Um goblin bruxo", "", 3],
	"green_spell1": [null, null, "magic", "", "", 2],
	"green_spell2": [null, null, "magic", "", "", 3]
}
